# encoding=UTF-8
import numpy as np
#1 ndarray
lst1= [[1, 2, 3],[4, 5, 6]]
lst2= [[1, 2, 3],['a', 'b', 'c']]
print(type(lst1))
print(type(lst2))
np_list1=np.array(lst1)
print(type(np_list1))
np_list1=np.array(lst1,dtype=np.float)
#bool,int,int8/16/32/64/128,uint8/16/32/64/128,float,float16/32/64,complex 64/128
print(np_list1.shape)
print(np_list1.ndim)
print(np_list1.dtype)
print(np_list1.size)
print(np_list1.itemsize)
print(np_list1.nbytes)
#2 some arrays
print(np.zeros([2,4]))
print(np.ones([2,3]))
print("Random:")
print(np.random.rand(2,4))
print(np.random.rand())
print("RandomInt:")
print(np.random.randint(1,10))
print(np.random.randint(1,10,3))
print("Randomn:")
print(np.random.randn(2,4))
print(np.random.randn())
print("Choice:")
print(np.random.choice([10,20,30]))
print("beta:")
print(np.random.beta(1,10,100))
print(np.random.beta(1,10))
#3  array operations
lst=np.arange(1,11).reshape([2,-1])
lst1=np.arange(1,11)
print(lst)
print(lst1)
print("Exp:")
print(np.exp(lst))
print("Exp2:")
print(np.exp2(lst))
print("Sqrt:")
print(np.sqrt(lst))
print("Sin:")
print(np.sin(lst))
print("Log:")
print(np.log(lst))
lst=np.array([[[1,2,3,4],
               [4,5,6,7]],
              [[7,8,9,10],
               [10,11,12,13]],
              [[13,14,15,16],
               [17,18,19,20]]
])
print(lst)
print("Sum:")
print(lst.sum(axis=0))
print(lst.sum(axis=1))
print(lst.sum(axis=2))
print("Max:")
print(lst.max(axis=1))
print("Min:")
print(lst.min(axis=2))
lst1=np.array([10,20,30,40])
lst2=np.array([1,2,3,4])
print("Add:")
print(lst1+lst2)
print("Subtract:")
print(lst1-lst2)
print("Division:")
print(lst1/lst2)
print("Multiplication:")
print(lst1*lst2)
print("Exponentiation:")
print(lst1**2)
print(lst2**3)
print("Dot:")
print(np.dot(lst1.reshape([2,2]),lst2.reshape([2,2])))
print("Concatenate:")
print(np.concatenate((lst1,lst2),axis=0))
print("Vstack:")
print(np.vstack((lst1,lst2)))
print("Hstack:")
print(np.hstack((lst1,lst2)))
print("Split:")
print(np.split(lst1,2))
print("Copy:")
print(np.copy(lst1))
#4 liner
from numpy.linalg import *
print(np.eye(3))
lst=np.array([[1,2],[3,4]])
print("Inv:")
print(inv(lst))
print("T:")
print(lst.transpose())
print("Det:")
print(det(lst))
print("Eig")
print(eig(lst))
y=np.array([[5.],[7.]])
print(solve(lst,y))
#5 others
print("FFT:")
print(np.fft.fft(np.array([1,1,1,1,1,1,1,1,1,1,1])))
print("Coef:")
print(np.corrcoef([1,0,1],[0,2,1]))
print("Poly:")
print(np.poly1d([2,1,3]))
print(np.poly1d([3,2,1,3]))